apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - appName: one
        url: https://kubernetes.default.svc
      - appName: two
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{appName}}-guestbook'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/chengfang/argocd-example-apps.git
        targetRevision: HEAD
        path: appset/{{appName}}
      destination:
        server: '{{url}}'
        namespace: openshift-gitops
