apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-1
  template:
    metadata:
      labels:
        app: guestbook-1
    spec:
      containers:
        - name: guestbook-1
          image: tomcat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: guestbook-1
